### ISSUE TITLE
ssl-vision not compatible with ROS Melodic Morenia on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by mrlukasbos** [RoboCup-SSL/ssl-vision#109]
I am currently experiencing some issues with running SSL vision. I noted that OpenCV2 is required for ssl-vision, but ROS melodic needs at least OpenCV 3.2. Are there already any developments to use OpenCV3 for ssl-vision?

**Comment by g3force** [comment]
OpenCV is only required for the Neural Network Widget, which is not well maintained.
Are there any compilation errors when having OpenCV 3 installed? Otherwise, you should be fine using ssl-vision without OpenCV.

**Comment by mrlukasbos** [comment]
When forcing in Cmakelists.txt to use openCV3 the compilation breaks. 

When telling Cmakelists to use opencv2, while only having openCV3 installs makes the compilation succeed, but Basler Camera support breaks; which is quite a recent PR as far as I know. 

When having opencv2 installed, everything works perfectly.

**Comment by g3force** [comment]
oh, true. Basler Camera support requires OpenCV, too.

As far as I know, there is currently no plan to move to OpenCV 3.

**Comment by g3force** [comment]
with #124, ssl-vision requires OpenCV >= 3. I also fixed the compile issue in the basler capture module.

**Comment by joydeep-b** [comment]
@mrlukasbos @g3force Is this resolved now?

**Comment by g3force** [comment]
I can not test the basler support, but at least OpenCV 3 is required on master for some time now.

**Comment by mrlukasbos** [comment]
I forgot that this issue was open. The issue has in the meanwhile been resolved indeed.
