### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by maxaubel** [RoboCup-SSL/ssl-vision#111]
Hi!

I wanted to update my ssl-vision version, so I just deleted the previous one and cloned the most recent one. The problem is that `make` fails. It printed lots of protobuf related errors, so I reinstalled protobuf. But the errors keep appearing.

Take a look at the [outputs](https://github.com/RoboCup-SSL/ssl-vision/files/2498510/make_errors.txt) of `make`. What am I doing wrong?

EDIT: I'm using Ubuntu 18.04 btw

Thanks!

**Comment by g3force** [comment]
That's strange. Could you try #112 ? On Arch Linux, the build on master is currently indeed broken. Maybe you have some custom more recent library on your Ubuntu installed?
