### ISSUE TITLE
Support for Blackfly USB3.1 CAM

### ISSUE THREAD

**Issue by sakoyan** [RoboCup-SSL/ssl-vision#113]
hello!

I checked the Blackfly USB3.1 Camera operation.
But , I need to install the flycapture3 software to drivers.

Thank you.

operating camera (BFLY-U3-05S2C-CS)

**Comment by andre-ryll** [comment]
Hi,
this camera is not supported by the ssl-vision. Please feel free to add support for this camera.
If your issue is about a different topic, please explain.
Cheers,
Andre

**Comment by g3force** [comment]
Blackfly cameras will soon be supported with the Spinnaker SDK, see #122
