### ISSUE TITLE
Basler camera timing integer division

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboCup-SSL/ssl-vision#149]
There is an issue in  src/shared/capture/capture_basler.cpp, line 190,  (integer division), causing the basler camera timings to only be accurate up to a second. We (Roboteam Twente) fixed it downstream but we have a lot of changes on our fork so it's probably best if fixed separately here. It should be as simple as adding .0 behind the division denumerator.

**Comment by g3force** [comment]
Would you mind preparing a PR on a new branch anyway and test it to make sure the single change really fixes the issue?

**Comment by rolfvdhulst** [comment]
See #150, it did indeed fix the issue.
