### ISSUE TITLE
QGtkStyle could not resolve GTK on ubuntu 19

### ISSUE THREAD

**Issue by DongyaoZhu** [RoboCup-SSL/ssl-vision#156]
Hi, we are trying to use the library for the event in 2019, but cannot seem to have camera open in the software (it just shows a blue frame on the right). On launch it says as in the title on terminal. Can someone give some hint on what we should do to resolve this?

**Comment by g3force** [comment]
Could you give some more details? I'm not sure what you try to achieve and what error you get. What camera type are you using?

**Comment by DongyaoZhu** [comment]
Hi, we fixed it, it wasn't compatible with ubuntu 19.10 but was ok with 18.04. Sorry for the trouble.
