### ISSUE TITLE
opencv_imgcodecs is required but was not found

### ISSUE THREAD

**Issue by Droliven** [RoboCup-SSL/ssl-vision#169]
![报错](https://user-images.githubusercontent.com/37187316/77241397-7b3a4a80-6c2c-11ea-8687-941ef4309682.PNG)
I installed SSL-Vision in Ubuntu 14.04.6 in VMWare workstation 15 pro
After I type and run "cmake -DUSE_WHAT_SO_EVER=true .." in terminal, the error occurs,  just as what is showed in the picture above.

**Comment by g3force** [comment]
Ubuntu 14.04 is not supported anymore, please use at least Ubuntu 16, preferably Ubuntu 18.

Also, USE_WHAT_SO_EVER is a place holder ;)

**Comment by Droliven** [comment]
Tks
