### ISSUE TITLE
Change Spelling of SSL_FieldCicularArc to SSL_FieldCircularArc in messages_robocup_ssl_geometry.proto

### ISSUE THREAD

**Issue by jonathanlew** [RoboCup-SSL/ssl-vision#170]
We found that SSL_FieldCicularArc in messages_robocup_ssl_geometry.proto was missing an "r". The correct spelling is SSL_FieldCi**r**cularArc. We realize that fixing this can cause some backwards compatibility problems, but we just wanted to make the codeowners aware of the issue

**Comment by g3force** [comment]
Good catch. I also came across it once. It it wrong for several years already.

Anyhow, I've created a fix. Regarding the compatibility: The name of messages and fields is not transmitted, so unless someone copies the updated .proto file into their software, this does not effect compatibility. And the difference should be detected by the compiler anyway.
