### ISSUE TITLE
No Thresholding Results After YUV Calibration

### ISSUE THREAD

**Issue by YoungsonZhao** [RoboCup-SSL/ssl-vision#172]
I use 1394 cameras. I did the YUV calibration following the instructions of https://github.com/RoboCup-SSL/ssl-vision/wiki/color-segmentation-configuration. After the YUV calibration, I set thresholded as True in Visualization, however, the thresholding results do not show, nothing changes in the visualizatin window. Could any one help me to fix this issue?

**Comment by g3force** [comment]
I little bit more information would be helpful. Like screenshots and console output.

**Comment by YoungsonZhao** [comment]
> I little bit more information would be helpful. Like screenshots and console output.

The code was downloaded from github and nothing changed. I just compiled it with using 1394 camera option. And the operation system is Ubuntu 18.04.
![终端截图1](https://user-images.githubusercontent.com/8778220/80339151-9b46d480-8890-11ea-8ef4-d94b73a822d6.png)
![终端截图2](https://user-images.githubusercontent.com/8778220/80339155-9da92e80-8890-11ea-98b9-50779c72c7b8.png)
![终端截图3](https://user-images.githubusercontent.com/8778220/80339158-9f72f200-8890-11ea-910b-388fb4bfeb18.png)
![终端截图4](https://user-images.githubusercontent.com/8778220/80339162-a0a41f00-8890-11ea-9776-70afc01e4dfc.png)
![终端截图5](https://user-images.githubusercontent.com/8778220/80339166-a26de280-8890-11ea-90ca-ea0cf0e1194e.png)

![界面](https://user-images.githubusercontent.com/8778220/80339135-92560300-8890-11ea-8c7c-1f3cbd47b36f.png)

**Comment by YoungsonZhao** [comment]
> I little bit more information would be helpful. Like screenshots and console output.
This video shows the problem.
[https://www.youtube.com/watch?v=A70XjHFzS4U](url)

**Comment by g3force** [comment]
I suggest to start with respecting the very first warning in the log ;) That's quite important. Btw, please rather share the log as text snippet.

If this does not help, please also share your configuration files. You can use the `backup.sh` script to create a snapshot with all relevant config files.

**Comment by YoungsonZhao** [comment]
> I suggest to start with respecting the very first warning in the log ;) That's quite important. Btw, please rather share the log as text snippet.
> 
> If this does not help, please also share your configuration files. You can use the `backup.sh` script to create a snapshot with all relevant config files.

Thanks for your advice.

**Comment by g3force** [comment]
Have you found and solved the issue?

**Comment by YoungsonZhao** [comment]
> Have you found and solved the issue?

This issue is not solved. I just downloaded an elder version committed on July 2, 2019 and the issue did not happen anymore.

**Comment by g3force** [comment]
There is an issue with the image mask. It is not initialized correctly with a fresh config. I'll fix it later, but if you want to test it, you just need to clear the mask once in the mask view on the right.
