### ISSUE TITLE
qt4 support / CircleCI

### ISSUE THREAD

**Issue by emielsteerneman** [RoboCup-SSL/ssl-vision#196]
I was wondering if qt4 support is still needed. I assume most SSL-Vision users run Ubuntu. qt4 has been [removed](https://ubuntuhandbook.org/index.php/2020/07/install-qt4-ubuntu-20-04/) from Ubuntu from 20.04 onward. qt5 seems to work well. Additionally, the qt4 CircleCI check is, for me personally, [hindering development](https://github.com/RoboCup-SSL/ssl-vision/pull/195) https://app.circleci.com/pipelines/github/RoboCup-SSL/ssl-vision/281/workflows/0739e6b7-a421-4906-9c75-7358ed6cb9c6/jobs/950

**Comment by g3force** [comment]
Yeah, I agree. Should be feasible for people to upgrade to at least Ubuntu 20.04, to run ssl-vision.

Could you create a PR with the removal? The flags in CMake and the CircleCI Job should be removed then.

**Comment by emielsteerneman** [comment]
Created the PR [here](https://github.com/RoboCup-SSL/ssl-vision/pull/197) https://github.com/RoboCup-SSL/ssl-vision/pull/197
