### ISSUE TITLE
build fails with -DUSE_DC1394=false when libdc1394 is not installed

### ISSUE THREAD

**Issue by kenshin33** [RoboCup-SSL/ssl-vision#198]
compilation fails to finish complaining a bout a missing header provided by libdc1394

[this line](https://github.com/RoboCup-SSL/ssl-vision/blob/64f3f29929ccd3f7cb316102454decd624056d06/src/app/capture_thread.h#L24) should be guarded by either DC1394 or  NO_DC1394_CONVERSIONS as it was done  in https://github.com/RoboCup-SSL/ssl-vision/commit/979dc066892153df1e3ab6f46ea3177873352721

**Comment by g3force** [comment]
Interesting. Looks like nobody ever tested this before.

Would you mind creating a PR with your suggested fix?

We could also remove the package from the installation script and only mention the required package in the Readme.

**Comment by kenshin33** [comment]
sure thing . But for the record, I have no idea what this project does or how it works. I just stumbled on this issue while helping someone build it!

**Comment by kenshin33** [comment]
fixed in https://github.com/RoboCup-SSL/ssl-vision/pull/199
