### ISSUE TITLE
YUV calibration

### ISSUE THREAD

**Issue by xuanmingShang** [RoboCup-SSL/ssl-vision#211]
![b060120693163cb0f608814b3cd7388](https://github.com/RoboCup-SSL/ssl-vision/assets/99722675/eceec19e-a6e0-47e4-a88a-6f652dbda57b)
As you can see in the picture, there should be some colors in the position of the red frame, but it missed. How can I solve this?

**Comment by g3force** [comment]
Please provide more information on your exact setup.
