### ISSUE TITLE
Provide an example of known working hardware

### ISSUE THREAD

**Issue by Hawk777** [RoboCup-SSL/ssl-vision#32]
At the committee meeting, it was brought up that it would be helpful if the SSL-Vision documentation included a complete build of known-working hardware (the computer and Firewire card models as well as the cameras) for new teams to look at to get started.

**Comment by g3force** [comment]
Those information are present in the current documentation: https://github.com/RoboCup-SSL/ssl-vision/wiki/requirements-installation
