### ISSUE TITLE
USB Camera / OpenCV Support Integration

### ISSUE THREAD

**Issue by zaidpirwani** [RoboCup-SSL/ssl-vision#33]
Hi,

So, we are working with USB cameras, specifically the Playstation 3 EYE Camera, and in order to use that we need USB Camera and OpenCV Support, which we have from an OLD fork of ssl-vision which is here
https://github.com/xuyuan/ssl-vision

Can someone help me, or guide me a bit on how I can integrate the OpenCV support in the current version of ssl-vision, i.e. this repo.

**Comment by joydeep-b** [comment]
Hi Zaid,

There is no official USB support yet. It would be great if you could create
a patch or pull-request with USB camera support. To add USB camera support,
you will need to define a new capture source. For a simple example, see
capturefromfile.h, .cpp in ssl-vision/src/shared/capture/ . Also see how it
is instantiated in ssl-vision/src/app/capture_thread.cpp .

-Joydeep

**Comment by joydeep-b** [comment]
V4L Support added with #35 (Thanks, Eric!).
