### ISSUE TITLE
small DVR'd set of data for calibration and gameplay

### ISSUE THREAD

**Issue by ezavesky** [RoboCup-SSL/ssl-vision#38]
a DVR'd set of data for (a) calibration and (b) a few seconds of gameplay would be spectacular.  It would be a big technical challenge to introduce test suites for understanding new plugins -- and making sure changes don't break things -- so the next best thing would be some DVR data.  I was thinking of these two scenarios, but am interested in others that the community may have for examples.
- Initial calibration for one or more color patterns
- A few seconds of gameplay from one or more cameras to visualize and understand what things _should_ look like when they're working correctly.

**Comment by g3force** [comment]
I added a small section to the Wiki-Home: https://github.com/RoboCup-SSL/ssl-vision/wiki

I had this setup in my local ssl-vision folder anyway and really like the idea to provide new users with a ready to run config.

Anyone willing to test it?
