### ISSUE TITLE
ROS output and input hooks required

### ISSUE THREAD

**Issue by ezavesky** [RoboCup-SSL/ssl-vision#42]
With the prevalence of [ROS](http://www.ros.org/) and it's wealth of robotic-friendly community contributions, we seek to bring components of ssl-vision to a ROS environment.  This issue is more of a request for information from the ssl-vision community on what it thinks is the best way to do that.  The following list iterates the requirements for this implementation and is offered in hopes of attracting guidance.
- [ ] ROS output of detected regions and detected robot codes
  - **Proposal**: It looks like the easiest way to achieve this is to add ROS output as another plugin.  
  - _request for information_ This could be implemented as a conditional in the CMake files so that not all ssl-vision users would need updated dependencies
  - additionally, more for prudence than a perceived functional conflict, the current broadcast/UDP plugin could be conditionally deactivated when the ROS plugin is running
- [ ] ROS input of frames from an alternate source (e.g. a [rectified image](http://wiki.ros.org/image_proc))
  - **Proposal**: similar to the point above, adding a new ROS-based image source plugin appears to be the easiest/appropriate way to introduce alternate inputs.
  - Also, because the ROS environment has a means for ["bagging messages"](http://wiki.ros.org/Bags) messages, the DVR plugin within ssl-vision would be conditionally deactivated when the ROS plugin is running
- [ ] minimization of running interactive (Qt) components such that a "head-less" environment is possible within a standard ROS node
  - **Proposal**: this is the most complicated modification proposed, which needs the most guidance. Some community-based postings for this topic have been found and give some hope to just implementing an alternate stack ([headless Qt GPU](http://stackoverflow.com/questions/14347286/headless-qt4-opengl-application), [claims that alternate client can be created](http://stackoverflow.com/questions/25312250/run-qprocess-with-and-without-a-gui), [claims of using a fake X server](https://forum.qt.io/topic/3751/qtwebkit-without-gui/5))
  - As a very aggressive alternative, an alternate stack could be written that directly uses the underlying [cmvision2](http://www.cs.cmu.edu/~jbruce/cmvision/) core vision and pattern libraries.  However, since the VarType objects are so deeply embedded in the libraries this may not be achievable.

**Comment by ezavesky** [comment]
@MichaelEischer  and @joydeep-b any preference or opinion for this issue/request?

**Comment by joydeep-b** [comment]
A ROS standalone shim should be easy to add as a standalone client. 
I am not too keen on adding ROS support directly to the ssl-vision main app for the following reasons:
1. It will add to the dependencies for the main app for an optional feature. Adding it as an agnostic feature would require some hacking.
2. Latency and frame rate performance of ssl-vision is crucial, and teams rely on it. Adding ROS support might adversely affect performance.

I like the idea of a headless version of ssl-vision, with a GUI frontend as an optional add-on runtime,  rather than a requirement. This would require significant refactoring of the code, however.

**Comment by ezavesky** [comment]
@joydeep-b Thanks for the feedback.  While having a stand-alone ROS node is the eventual intention, what do you think about ROS output as (a) something conditionally turned on via a CMake or command line option and (b) a plugin in the stack such that it does not influence latency, much as the current UDP broadcast scheme is threaded and does not inhibit the capture side?  I think this middle ground may be useful for groups that already have work in ROS and would like to leverage its features in addition to the ssl-vision base stack.

I agree that headless will be a challenge.

**Comment by g3force** [comment]
During my master thesis, I wrote a small converter that reads ssl-vision data and publish the data to ROS topics: https://github.com/g3force/ros_ssl_robot
I agree with Joydeep, that we should not add any ROS dependencies directly to ssl-vision.
If you have a dedicated ROS converter that could be useful for other teams, we could just add it as separat repository and reference it in the docs.
