### ISSUE TITLE
relax hard coded requirements for existing color pallette

### ISSUE THREAD

**Issue by ezavesky** [RoboCup-SSL/ssl-vision#46]
While the current set of 9 colors works well in general for pattern detection, it's likely that we can optically optimize them for more lighting robustness.  One simple example of this is experimenting for robustness in grayscale such that shadows, various temperatures of indoor lighting, and other effects are minimized.

Below is a living list of modifications that may be required to achieve this robustness:
- [ ] Remove hard-coded of specific colors in team detection (like [here](https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/shared/cmpattern/cmpattern_teamdetector.cpp#L64) and [here](https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/shared/cmpattern/cmpattern_teamdetector.cpp#L298) and [here](https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/app/plugins/plugin_detect_robots.cpp#L74)).
- [ ] Allow the geometry and rough region placement of patterns to be precisely mapped to a larger set of colors.  Depending on tests, this may require loading and using actual image data in [team pattern initialization](https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/shared/cmpattern/cmpattern_teamdetector.cpp#L147) instead of relying on color space separation alone.
  - [ ] Optionally, allow several more colors to be created as candidates during new LUT initialization [here](https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/shared/util/lut3d.h#L349)

**Comment by g3force** [comment]
Based on the discussions in #39 I would suggest to close this issue. We only use the standard patterns, so there is no need to generalize team patterns.
@ezavesky feel free to reopen the issue, if you feel like there is still something to do.
