### ISSUE TITLE
Setup for half field?

### ISSUE THREAD

**Issue by justbuchanan** [RoboCup-SSL/ssl-vision#55]
Is it still possible to setup ssl-vision with 2 cameras for a half-size field?  And if so, is there any documentation on how to do this?  I'm a little confused on what camera indices to use and how to setup the control points.

**Comment by hbritto** [comment]
As far as I know, you'd need to change the parameter in _mainwindow.cpp_ sent to the constructor of _MultiStackRobocupSSL_, from `multi_stack=new MultiStackRoboCupSSL(opts, 4);` to `multi_stack=new MultiStackRoboCupSSL(opts, 2);`.
After that, you'd have to change the _kNumControlPoints_ in _camera_calibration.h_, inside the class _AdditionalCalibrationInformation_.

**Comment by MichaelEischer** [comment]
There's no need to make any changes to the ssl-vision source code. Just enable only two cameras and reconfigure the field lines. I should be able to upload a working configuration for two cameras tomorrow.

**Comment by AlexanderDanzer** [comment]
For the control point setup, take a look at the [wiki](https://github.com/RoboCup-SSL/ssl-vision/wiki/camera-calibration).
