### ISSUE TITLE
Errors compiling with OpenCV Major Version >= 3

### ISSUE THREAD

**Issue by joydeep-b** [RoboCup-SSL/ssl-vision#63]
The Neural Net Color Calibration code is incompatible with CV_VERSION_MAJOR >= 3, needs version checks to wrap OpenCV API calls.

**Comment by joydeep-b** [comment]
OpenCV Migration guide:
http://docs.opencv.org/3.1.0/db/dfa/tutorial_transition_guide.html#tutorial_transition_hints_ml

**Comment by g3force** [comment]
I will have a look at this

**Comment by g3force** [comment]
There is quite a lot of difference between OpenCV 2 and 3 in the ml package. I converted the code to OpenCV 3, but predictions seems to be wrong: https://github.com/g3force/ssl-vision/tree/neural_calib_CV3

For now, the PR above will at least fix the build on systems with OpenCV 3.
