### ISSUE TITLE
having trouble in detecting pattern

### ISSUE THREAD

**Issue by andira14** [RoboCup-SSL/ssl-vision#69]
Hi, I'am having trouble detecting the patterns and tweaking the marker settings but I can detect the ball just fine. I've done every instructions needed but then got stuck on the tweaking part. I'm using v4l for the stream. I detected the blob just fine but couldn't get it to show on the graphical client. Sorry, I'm new to this and need some directions. thank you.

![screenshot from 2016-12-21 21 14 27](https://cloud.githubusercontent.com/assets/24704940/21406274/9963635a-c7c2-11e6-88a4-2d6b202853fa.png)

**Comment by g3force** [comment]
For the robot detection the size of the blobs matter. You see the configuration in your screenshot.
Either you have to change the min/max values of the blobs or you move the camera sufficiently far away from the robot (3.5m is the default).

**Comment by joydeep-b** [comment]
The geometry calibration also needs to be accurate. The pattern matching algorithm using computed physical distances between the dots.
