### ISSUE TITLE
Begginer's Doubt about SSL vision and Robot Strategy

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#71]
Hello everybody,

I have a doubt basic doubt and Excuse my ignorance in SSL vision, but could anyone help to explain about, 
Is possible to put the game strategy in SSL vision, and SSL vision sends commands to the robot? 
![ssl - robot](https://cloud.githubusercontent.com/assets/29002199/26522433/1280a31c-42d7-11e7-8625-63d7250b7943.png)

Or SSL vision only receives the image and provides the image information to the program Strategy that sends commands to robots?
![ssl - program - robot](https://cloud.githubusercontent.com/assets/29002199/26522434/161dd04e-42d7-11e7-9e4a-3427888d997b.png)

Thank you all

**Comment by MichaelEischer** [comment]
The way sslvision works is similar to your second flow chart. However, sslvision already processes the images and only sends robot and ball positions to your strategy program.

For the RoboCup a shared sslvision instance runs for each field. Therefore it won't be possible for teams to integrate their own strategy into sslvision. Just use the information that's sent over the network by sslvision and process it in a separate strategy program.

While it could be possible to modify sslvision to send the raw camera images to the teams over LAN, I highly doubt that such a setup would be reliable.
