### ISSUE TITLE
Issue in SSL vision installation

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#72]
Hello,

I tried to install SSL-vision in ubuntu in Virtualbox, but I had problem in this step:
![conf2](https://cloud.githubusercontent.com/assets/29002199/26553939/447c4004-4464-11e7-956f-3b89c4a9a4c7.png)

In my virtual machine, the bin directory does not contain binaries "vision", "client" and "graphicalclient":
![conf](https://cloud.githubusercontent.com/assets/29002199/26554007/94d0b396-4464-11e7-8cca-0cd9784b59ed.png)

Does anybody know if I did anything wrong? or if SSL does not work in Virtual machines?

Thanks!

**Comment by JetseVerschuren** [comment]
The manual says that the `./bin` should contain three binaries but you showed the content of the `/bin` folder. Note the dot at the beginning. It means that the bin folder is relative to the folder you cloned ssl-vision into. So you should probably be looking for the `/root/ssl-vision/bin` or the `/home/USER/ssl-vision/bin` directory for the three binaries.

**Comment by Xandao89** [comment]
@JetseVerschuren Now I checked ssl-vision/bin, and it's OK, the binaries are there.
Could you please solve another question?
Is possible I capture image using USB camera or Integrated Webcam in Laptop?
I tried to open my integrated camera on laptop to capture image, but the only thing that changed in camera 0 that the screen turn to green, and I changed the parameters of camera module to Video 4 Linux
![virtualbox_ubuntu_29_05_2017_16_20_13](https://cloud.githubusercontent.com/assets/29002199/26560184/ea6dba3a-448a-11e7-9cb8-35c92d961f89.png)

**Comment by JetseVerschuren** [comment]
I don't have that green screen.
Can you post your operating system and terminal log?

**Comment by Xandao89** [comment]
Hello my friend,

My problem was the RAM of the process, as I installed the program in a Virtual Machine, the memory to run the application was not enough, Now I changed to a partition with Ubuntu, and the program is working well, 

Tks
