### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#73]
Hello,

I am trying to calibrate my camera, But I can't positionate the point in the right place to test the calibration, is there any order to put the points to "Do initial calibration"

Ps.: I tryed to put the points at the corners of each quarter, in several orders, but the field image didn't adjust to the field.

![captura de tela de 2017-06-02 16-30-31](https://cloud.githubusercontent.com/assets/29002199/26741702/d77ee862-47b0-11e7-8449-1c14ded452ce.png)

Thanks!

**Comment by MichaelEischer** [comment]
Most of the calibration procedure is explained in https://github.com/RoboCup-SSL/ssl-vision/wiki/camera-calibration .
The control point should be arranged in counter-clockwise order (at least I think so). Make sure to adjust the control point field coordinates to something reasonable.
