### ISSUE TITLE
Save settings in SSL

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#74]
Hello,

I want to know if only are having this problem, I couldn't save anything I changed in SSL vision.
Example: I calibrated the field and YUV colors Thresholding, but even I click in  "Save settings" and after click in "X" to close the program, when I open again the calibration had been lost,
Could anyone help me about this, please?

**Comment by JetseVerschuren** [comment]
Do you still have this problem?

**Comment by Xandao89** [comment]
Yes, Still have the problem,
Is possible to save our calibration in SSL, so next time turn on the PC the calibration are done?

**Comment by MichaelEischer** [comment]
The calibration should be saved automatically when ssl-vision exits. Do you see any warnings/errors on the console when clicking "Save settings" or when exiting ssl-vision?
How exactly do you start ssl-vision? For example: cd ssl-vision; bin/vision
Are the xml configuration files (settings.xml, robocup-ssl*.xml) writeable by your current user?

**Comment by Xandao89** [comment]
I start SSL Vision clicking in the bin directory:
![captura de tela de 2017-08-08 14-22-00](https://user-images.githubusercontent.com/29002199/29092904-4f31b97a-7c5e-11e7-9348-80ea13259055.png)

I tried to start Vision in the Terminal, but was not possible:
![Uploading Captura de tela de 2017-08-08 14-22-26.png…]()
When I tried the command vision, the message ¨Do not Find the command¨

**Comment by Xandao89** [comment]
When I click in save settings in SSL, any message error appears, but when I open the programa again, the settings that I changed are unchanged.

**Comment by joydeep-b** [comment]
You need to run ssl vision from the _main ssl-vision directory_
https://github.com/RoboCup-SSL/ssl-vision#running
```
./bin/vision
```
