### ISSUE TITLE
My robot do not appears in graphicalclient

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#75]
Hello, I already calibrate YUV, and configurate a team inside of vision, but when I open the graphicalClient, my robot do not appears, is there any setting that need to be changed before open graphicalClient?

![captura de tela de 2017-06-12 17-51-37](https://user-images.githubusercontent.com/29002199/27054573-cefd35ce-4f97-11e7-9528-9d7fb9ba831e.png)

![captura de tela de 2017-06-12 17-17-01](https://user-images.githubusercontent.com/29002199/27054714-47e6079a-4f98-11e7-9fde-00e8382b536e.png)

**Comment by JetseVerschuren** [comment]
Can you try to run the client (the commandline one) and post the output?

**Comment by Xandao89** [comment]
Hello, my problem was caused by the Wrong Dimensions of the field, my field is smaller then the official, and I didn't considered this... So, a friend said that if you have different dimensions of the field you need adjust, in order to the robot can be recognized, So I made in the lab, only goal area, and calibrate again , field and YUV colors, now the robot appears in the graphical Client:

![captura de tela de 2017-06-13 16-22-49](https://user-images.githubusercontent.com/29002199/27100457-91d7ba44-5054-11e7-9bbd-68a128151281.png)
I calibrate only a goal area.

![captura de tela de 2017-06-13 16-14-08](https://user-images.githubusercontent.com/29002199/27100460-95f6f842-5054-11e7-8f28-513998df8425.png)

thank you all
