### ISSUE TITLE
How to access the packet after click in Publish

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#79]
Hello,

My robot appears in graphicalClient, and as I read here, the next step to get the localization of the robot, is Publish the packet with the information, right?
But how can I check this packet? after I ¨Publish¨, where can I check the robot information?

Thank you all in advance

![captura de tela de 2017-08-09 15-08-43](https://user-images.githubusercontent.com/29002199/29144238-978896a0-7d2e-11e7-867d-12fce582153b.png)

**Comment by g3force** [comment]
Check the wiki for details on the communication:
https://github.com/RoboCup-SSL/ssl-vision/wiki/communication
