### ISSUE TITLE
Error to compile program to export SSL data

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-vision#80]
Hello everybody

I tested a simple program to export localization data from SSL,
follows the program:

[exemplo.txt](https://github.com/RoboCup-SSL/ssl-vision/files/1243375/exemplo.txt)

But when I try to compile the program in terminal this error appears:

ubuntu@ubuntu:~/Documents/test$ g++ exemplo.cpp
exemplo.cpp:9:46: fatal error: messages_robocup_ssl_geometry.pb.h: Arquivo ou diretório não encontrado (No input files)
compilation terminated.

Could you please help me to find what is the problem ?

**Comment by MichaelEischer** [comment]
You need to compile the corresponding protobuf definition (.proto-file) using protoc (Protobuf compiler)

**Comment by JetseVerschuren** [comment]
Can you run this `find -name '*.h'` in the directory you cloned ssl-vision in?
