### ISSUE TITLE
New field geometry

### ISSUE THREAD

**Issue by leonardoSCosta** [RoboCup-SSL/ssl-vision#89]
Hi, i've recently downloaded the latest version of ssl-vision but it still have the old defense zone, is there something I need to do to change it ?

**Comment by g3force** [comment]
Hi, the changes are not merged to the master yet. They are included in PR #88. You are welcome to test it and comment the PR so that we can merge it to master.

**Comment by leonardoSCosta** [comment]
Ok, thank you.
