### ISSUE TITLE
Coordinates in real field

### ISSUE THREAD

**Issue by maxaubel** [RoboCup-SSL/ssl-vision#92]
![image](https://user-images.githubusercontent.com/28493557/38461004-4ef780aa-3a9c-11e8-892d-c576184a6b18.png) (Not quite the best illumination)

We are struggling recently trying to assign the coordinates of our control points in the field, but we fail doing so. Our camera only sees one area, which includes a penalty area (idk if that's the real word for it). But as you can see, when click on "Do initial calibration", it messes up with the geometry of the field. Could you guys please tell us which coordinates should we put in there? That information will be very useful for our team. 

Kind regards,
AISoccer USM

**Comment by g3force** [comment]
Have you tried pressing reset, then several times initial calibration? Sometimes, the model messes up if you had done the initial calibration with bad control points.
The control points seem to be correct, though I can not really recommend using only the penalty area. You will probably get an imprecise result.
Btw.: You do not need to calibrate field green. It is not used anywhere, but still needs more calculation time.

**Comment by maxaubel** [comment]
As the issue is sloved, i'm going to close it. If anyone has some issues with the calibration process, I can also help guide the process.

**Comment by g3force** [comment]
btw: you can add arbitrary lines and they are used for line detection. So you could add lines somewhere else too. That may help, but your solution also works.
