### ISSUE TITLE
Can't use two cameras simultaneously

### ISSUE THREAD

**Issue by leonardoSCosta** [RoboCup-SSL/ssl-vision#95]
Hello, we've been having some troubles when trying to use more than one camera in the same pc, when we try to start capture on the second camera it gives an error saying "libdc1394 error: juju: Failed to allocate iso resources
CaptureDC1394v2 Error: unable to setup capture. Maybe selected combination of Format/Resolution is not supported?
", I think all the configuration is ok, our ssl-vision client is up to date with the latest master version on github.

**Comment by g3force** [comment]
Have you connected both firewire cameras to the same Firewire card? We usually use one card per camera.

**Comment by leonardoSCosta** [comment]
Yes, we did that, so it isn't recommended to try to use more than one camera per card ?

**Comment by joydeep-b** [comment]
You can use more than one camera per card only if the card has multiple bus
controllers. Two cameras require more bandwidth than can be supported by a
single bus.
