### ISSUE TITLE
Update default configuration

### ISSUE THREAD

**Issue by g3force** [RoboCup-SSL/ssl-vision#98]
* Remove obsolete teams
* Set default number of robots

**Comment by adakamakiri** [comment]
At the 'Global > Ball Detection > Geometry Filters > Ball-In-Field Extra Space (mm)',
I found the 30.0 mm. 
For the ball placement, the ball has to be shown outside of the field until 300 mm before the wall.

**Comment by g3force** [comment]
you are right, I changed it.
